apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: diabetes-api-ml-apirule
  namespace: asif-test
  labels:
    app.kubernetes.io/name: diabetes-api-ml
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - "asif-test.c-321a6c0.stage.kyma.ondemand.com"
  service:
    name: diabetes-api-ml-service
    port: 80
  rules:
    - path: /{**}
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      noAuth: true
