apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-api-ml
  labels:
    app: diabetes-api-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-api-ml
  template:
    metadata:
      labels:
        app: diabetes-api-ml
    spec:
      containers:
      - name: diabetes-api
        image: asif1993/second_ml:6fccfb2
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_URI
          value: "https://model-registry/models/diabetes/v3/model.pkl"
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-ml-service
  namespace: asif-test  
spec:
  selector:
    app: diabetes-api-ml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
